/*******************************************************************************
 * Copyright © 2010-2023. Cloud Software Group, Inc. All rights reserved.
 *******************************************************************************/
/*
 * generated by Xtext
 */
package com.jaspersoft.studio.data;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SqlRuntimeModule extends com.jaspersoft.studio.data.AbstractSqlRuntimeModule {

}
